//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourthCoffeeAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationLog
    {
        public System.Guid ApplicationLogId { get; set; }
        public string MessageType { get; set; }
        public string Definition { get; set; }
        public string LogDate { get; set; }
        public Nullable<int> MessageCode { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
