//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourthCoffeeAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerAccount()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public System.Guid CustomerAccountId { get; set; }
        public Nullable<int> AccountType { get; set; }
        public System.Guid CustomerId { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string CreditCardNumber { get; set; }
        public string Issuer { get; set; }
        public Nullable<decimal> IncrementAmount { get; set; }
        public string ExpirationDate { get; set; }
        public string Pin { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
