//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourthCoffeeAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid TransactionId { get; set; }
        public Nullable<System.Guid> MasterTransactionId { get; set; }
        public Nullable<System.Guid> CustomerAccountId { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> TransactionTime { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> TotalServiceFee { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> RunningBalance { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MasterTransaction MasterTransaction { get; set; }
        public virtual CustomerAccount CustomerAccount { get; set; }
    }
}
