//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourthCoffeeAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoidTransaction
    {
        public System.Guid VoidTransactionId { get; set; }
        public Nullable<System.Guid> MasterTransactionId { get; set; }
        public Nullable<System.Guid> RefundTransactionid { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual MasterTransaction MasterTransaction { get; set; }
        public virtual RefundTransaction RefundTransaction { get; set; }
    }
}
